repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: cargo-fmt
        name: task lint:fmt
        entry: task lint:fmt
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: task lint:clippy
        entry: task lint:clippy
        language: system
        types: [rust]
        pass_filenames: false
